### ISSUE TITLE
Exceptions when the Virgin V6 box is turned off

### ISSUE THREAD

**Issue by davesmeghead** [bertbert72/HomeAssistant_VirginTivo#11]
When the Virgin box is turned off, I assume that it disables the ethernet interface as I start getting exceptions from the python script as follows:

> 2019-01-20 10:28:27 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.virgin_v6 fails
Traceback (most recent call last):
  File "/config/custom_components/media_player/virgintivo.py", line 529, in connect
    data = self._sock.recv(bufsize).decode()
OSError: [Errno 9] Bad file descriptor
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/virgintivo.py", line 462, in update
    self.connect()
  File "/config/custom_components/media_player/virgintivo.py", line 544, in connect
    self._sock.connect((self._host, self._port))
ConnectionRefusedError: [Errno 111] Connection refused

Can you please add a python exception handler for this specific case to stop the log file being filled with these exceptions

**Comment by bertbert72** [comment]
This stuff is already wrapped in an exception handler.  I'll have to have a dig to see why it's not handling this.

**Comment by davesmeghead** [comment]
OK thankyou for taking a look, and I have a Virgin V6 box if that helps. This exception repeats every 10 minutes in the log file so it's not exactly filling it but thought you should know. I've just updated HA to the latest release and the exception info is now

2019-01-26 08:40:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.virgin_v6 fails
Traceback (most recent call last):
  File "/config/custom_components/media_player/virgintivo.py", line 529, in connect
    data = self._sock.recv(bufsize).decode()
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/virgintivo.py", line 462, in update
    self.connect()
  File "/config/custom_components/media_player/virgintivo.py", line 544, in connect
    self._sock.connect((self._host, self._port))
ConnectionRefusedError: [Errno 111] Connection refused
2019-01-26 08:40:59 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.virgin_v6 fails
Traceback (most recent call last):
  File "/config/custom_components/media_player/virgintivo.py", line 529, in connect
    data = self._sock.recv(bufsize).decode()
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/virgintivo.py", line 462, in update
    self.connect()
  File "/config/custom_components/media_player/virgintivo.py", line 544, in connect
    self._sock.connect((self._host, self._port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by davesmeghead** [comment]
I mean that it's on standby, the LED is red on the front. I don't have keep_connected set to anything, here's my HA config, I've blanked out the host value
```
- platform: virgintivo
  default_is_show: true
  scan_interval: 5
  show_packages: Free-to-air,Player,Mix
  tivos:
    1:
      name: Virgin V6
      host: TIVO-CXXXXXXXXXXXXXXX
  guide:
    picture_refresh: 30
  channels:
    100:
      name: Virgin Media Highlights
      package: Mix
 etc.
```

**Comment by bertbert72** [comment]
Probably going to need the debug logs to see why it is happening.  Add this to your configuration.  It'll add a lot of stuff into your log but you can turn it back off once the error happens.

```
logger:
  default: error
  logs:
    custom_components.media_player.virgintivo: debug
```
Note that this is general configuration, not part of the component specific config, so it goes out in the main bit of the configuration.yaml.

**Comment by bertbert72** [comment]
Or actually, this might work, bearing in mind I can't replicate the problem so can't check.

Change line 554 to:

`
            except (socket.gaierror, OSError):
`

**Comment by davesmeghead** [comment]
OK so I replaced line 554 with "except (socket.gaierror, OSError):" and all I get in the log file from it is:
2019-01-26 10:56:58 ERROR (Thread-460) [homeassistant.core] Error doing job: Unclosed client session

So I put the line back to how is was and with debug logging I got the attached log file, note that I copied my log file before zipping it as I replaced all the TIVO references to have XXXXXX in them. Also, please ignore the harmony errors in the log to 192.168.0.168.

[home-assistant - Copy.zip](https://github.com/bertbert72/HomeAssistant_VirginTivo/files/2798934/home-assistant.-.Copy.zip)

Any help is much appreciated

**Comment by bertbert72** [comment]
Ok, try the update on the _fix-oserror_ branch (https://raw.githubusercontent.com/bertbert72/HomeAssistant_VirginTivo/fix-oserror/virgintivo.py).

You can turn off debug unless it still throws errors.

**Comment by bertbert72** [comment]
No probs, just happy that someone else is actually getting some use out of it.
