### ISSUE TITLE
Error while setting up virgintivo platform for media_player occurs 50% of the time after a restart of HA

### ISSUE THREAD

**Issue by craigo1975** [bertbert72/HomeAssistant_VirginTivo#123]
Hi,

I randomly get this error when I restart HA...around 50% of the time, so I'm thinking it may be a slow network issue?

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:365
integration: Media Player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 10:02:26 (1 occurrences)
Last logged: 10:02:26
Error while setting up virgintivo platform for media_player

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/virgintivo/media_player.py", line 230, in setup_platform
    hass.data[DATA_VIRGINTIVO].append(VirginTivo(extra[CONF_HOST], channels, tivo_id, extra[CONF_NAME],
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/virgintivo/media_player.py", line 330, in __init__
    self.get_guide_channels()
  File "/config/custom_components/virgintivo/media_player.py", line 341, in get_guide_channels
    for channel in channels_data["channels"]:
                   ~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

Any advice would be welcome to prevent this......

Below is my yaml setup:

# virgin tivo
media_player:
  - platform: virgintivo
    tivos:
      1:
        name: Virgin V6
        host: 192.168.0.76
        force_hd: true
    tvchannellists:
      enable: True

**Comment by ptruman** [comment]
Ditto to this (got it today)

**Comment by almoney** [comment]
I am not on the Virgin network, so I removed the failing call setting up the guide that is irrelevant to my TiVos.

**Comment by pjrish** [comment]
> I am not on the Virgin network, so I removed the failing call setting up the guide that is irrelevant to my TiVos.

@almoney I would also be interested in which lines of code were removed.  I’m not on the Virgin network either, and run into regular issues with loading the devices on startup.

**Comment by bertbert72** [comment]
Hi all, 

I'll probably repeat this a few timnes, but because of personal circumstances, I've little time to spend on this anymore.  It doesn't help that I've not had a Tivo for about 18 months as well.

The site providing the guide stopped doing so a few months ago.  You can disable the guide by adding this to your config

```
guide:
  enable_guide: False
```

**Comment by almoney** [comment]
> > I am not on the Virgin network, so I removed the failing call setting up the guide that is irrelevant to my TiVos.
> 
> @almoney I would also be interested in which lines of code were removed. I’m not on the Virgin network either, and run into regular issues with loading the devices on startup.

We have published corrections now.  Until the latest pull request I sent you need to add the 2 lines above to disable the guide.
