### ISSUE TITLE
Unable to turn on V6 box

### ISSUE THREAD

**Issue by bluesheep** [bertbert72/HomeAssistant_VirginTivo#19]
This may be related to the closed issue #11 but I'm having a problem with this component turning on my V6 box. It works fine to turn it off, and it works fine of my older tivos. just not on the new box. I can tell if the fix has been merged into the main but I have taken the current version.

the error I get in the log is:

```
2019-03-12 22:23:51 DEBUG (SyncWorker_13) [custom_components.media_player.virgintivo] Living Room Tivo: connection attempt gave [[Errno 9] Bad file descriptor]
2019-03-12 22:23:51 DEBUG (SyncWorker_13) [custom_components.media_player.virgintivo] Living Room Tivo: connecting to [192.168.1.19]
2019-03-12 22:23:52 DEBUG (SyncWorker_13) [custom_components.media_player.virgintivo] Living Room Tivo: disconnecting from [192.168.1.19]
2019-03-12 22:23:52 DEBUG (SyncWorker_13) [custom_components.media_player.virgintivo] Living Room Tivo: sending request [IRCODE STANDBY\r]
2019-03-12 22:23:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1835240464] [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1133, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 278, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 292, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/virgintivo.py", line 855, in turn_on
    self.tivo_cmd(cmd)
  File "/config/custom_components/media_player/virgintivo.py", line 503, in tivo_cmd
    self._sock.sendall(upper_cmd.encode())
OSError: [Errno 9] Bad file descriptor
```

**Comment by bluesheep** [comment]
I think I've identified some more details. If the tivo is on when home assistant starts, the commands work to turn the box on and off. If the device is off when the platform starts, you cannot turn it on.

If I manually turn the box on, from that point onwards things work the way they should. I'm looking at the initial states to see if I can work out what is going wrong.

**Comment by bertbert72** [comment]
The state of the box is always a bit problematic.  I'll need to have a look at this again, bearing in mind the limited info I can glean from the box itself.  Not sure when, but I will...  It should at least be able to handle turning it on.

**Comment by bertbert72** [comment]
That should be the problem fixed if you want to give it a go.

**Comment by bertbert72** [comment]
Latest version should have cleared up any remaining issues in this area.  Feel free to re-open or log a new issue if there are still any problems.
