### ISSUE TITLE
virgintivo: Error on device update!

### ISSUE THREAD

**Issue by garywilson4** [bertbert72/HomeAssistant_VirginTivo#20]
getting this error 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/virgintivo/media_player.py", line 571, in update
    self.get_guide_listings(self._guide_channel["channel_number"])
  File "/config/custom_components/virgintivo/media_player.py", line 353, in get_guide_listings
    hd_channel = self._channels[sd_channel][CONF_HDCHANNEL]
KeyError: 105
```
any help appreciated

**Comment by bertbert72** [comment]
That's strange.  Basically it is trying to look up the listings for channel 105 (I presume because the Tivo is on that channel) but it's not in the list of channels.

What does your yaml look like?  Are you using tvchannellists.com or have you defined the channels manually?

**Comment by garywilson4** [comment]
Manually maybe missed one I’ll look again thanks
