### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by garywilson4** [bertbert72/HomeAssistant_VirginTivo#21]
just updated to the latest version now getting this error
```
g*********w@virginmedia.com: Websocket failed: 'ubid-main'
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 405, in setup_alexa
    websocket = WebsocketEchoClient(login_obj, ws_handler)
  File "/config/deps/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 37, in __init__
    url += str(self._cookies['ubid-main'])
KeyError: 'ubid-main'
```
just wondering if i have to set something else up ?

**Comment by bertbert72** [comment]
That's an error from a different component - alexa_media.  I'm afraid I know nothing about that.

**Comment by garywilson4** [comment]
Oops sorry lol will move it
