### ISSUE TITLE
Integration fail to load on startup

### ISSUE THREAD

**Issue by ColinRobbins** [bertbert72/HomeAssistant_VirginTivo#70]
Hello,
I have been using this integration for a long time, but the 0.1.17 version fail to start correctly under Home Assistant 2021.2.1
I've set the log file to debug, which produces:
```
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Writing channels cache
2021-02-06 14:36:32 ERROR (SyncWorker_1) [custom_components.virgintivo.media_player] Could not fetch channel listings from https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK), error [Errno 13] Permission denied: 'virgin_tivo.pickle'
2021-02-06 14:36:32 ERROR (SyncWorker_1) [custom_components.virgintivo.media_player] No channel configuration available
2021-02-06 14:36:32 INFO (SyncWorker_1) [custom_components.virgintivo.media_player] Adding Tivo 1 - Virgin V6
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Force HD on TV is False
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Virgin V6: initialising connection to [192.168.10.41]
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Virgin V6: connecting to socket
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Virgin V6: connected OK
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Virgin V6: reading data from socket
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Virgin V6: response data [CH_STATUS 0103 LOCAL
]
2021-02-06 14:36:32 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Virgin V6: disconnecting from [192.168.10.41]
2021-02-06 14:36:33 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] Retrieving guide channels
2021-02-06 14:36:33 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] New channel [101]
2021-02-06 14:36:33 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] New channel [102]
...
2021-02-06 14:36:33 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] New channel [991]
2021-02-06 14:36:33 DEBUG (SyncWorker_1) [custom_components.virgintivo.media_player] New channel [998]
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: connecting to socket
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: connected OK
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: reading data from socket
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: response data [CH_STATUS 0103 LOCAL
]
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: disconnecting from [192.168.10.41]
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: changing to channel [0103]
2021-02-06 14:36:33 WARNING (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: incorrect channel configuration for channel [103]
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: guide found for channel 103 (103)
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Channel [103] in listings: False
2021-02-06 14:36:33 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Virgin V6: retrieving guide for channel 103 [https://web-api-pepper.horizon.tv/oesp/api/GB/eng/web//listings?byStationId=lgi-gb-prodobo-master:2122&byEndTime=1612622193000~1612665393000&sort=startTime]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [Live: Six Nations Rugby] [2021-02-06 13:30:00 - 2021-02-06 16:15:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [Live: Six Nations Rugby] [2021-02-06 16:15:00 - 2021-02-06 19:00:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [The Masked Singer] [2021-02-06 19:00:00 - 2021-02-06 20:30:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [The Voice UK] [2021-02-06 20:30:00 - 2021-02-06 22:00:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [ITV News] [2021-02-06 22:00:00 - 2021-02-06 22:15:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [Paul Sinha's TV Showdown] [2021-02-06 22:15:00 - 2021-02-06 22:50:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Added [Horrible Bosses] [2021-02-06 22:50:00 - 2021-02-07 00:50:00] to channel [103]
2021-02-06 14:36:34 DEBUG (SyncWorker_4) [custom_components.virgintivo.media_player] Next refresh for channel [103]: 2021-02-06 22:50
2021-02-06 14:36:34 ERROR (MainThread) [homeassistant.components.media_player] Error adding entities for domain media_player with platform virgintivo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/home/homeassistant/.homeassistant/custom_components/virgintivo/media_player.py", line 805, in device_state_attributes
    'base_channel_name': self._channels[self.get_sd_channel(self._channel_id)][CONF_NAME],
KeyError: None
```
A big of debugging shows this is because `self._channel_id` is `None`.

I have no idea why this is `None` but have added a [pull request](https://github.com/bertbert72/HomeAssistant_VirginTivo/pull/71) to test the value is not `None`.

**Comment by bertbert72** [comment]
I think both these issues have the same root cause. If self._channel_id is blank we've more problems than just that. Can you try the version here and let me know if it works for you? If so, I'll need to tidy up a bit since it's a bit hacky (not that that ever stopped me before).

https://raw.githubusercontent.com/bertbert72/HomeAssistant_VirginTivo/fix-cache-problem/custom_components/virgintivo/media_player.py

**Comment by ColinRobbins** [comment]
That link almost works!
I needed to change line 965 from
```
def get_channel_listings(config):
```
to
```
def get_channel_listings(config, cfg_dir):
```
then it seems to work.
Thanks!

**Comment by bertbert72** [comment]
Great, thanks Colin.  I had that in my local but didn't stick it on the branch version.  Muppet!  I'll get that on.  I've decided hacky is good since I now remember why I pulled that routine out of the tivo class...

**Comment by bertbert72** [comment]
That's it up.  Once again, thanks for doing all the leg work on this one.  Saved me trying to work it out :)
