### ISSUE TITLE
UFT-8 Codec error

### ISSUE THREAD

**Issue by nicks123** [bertbert72/HomeAssistant_VirginTivo#78]
Hi, Newbie to Home Assistant currently trying to integrate with Virgin Tivo. 

I'm unable to connect to Tivo Box, looking at log I see the following error. 

/config/virgin_tivo.pickle
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Config is

media_player:
  - platform: virgintivo
    tivos:
      1:
        name: Virgin V6
        host: HOSTNAME
    tvchannellists:
      enable: True

Any advise please?

**Comment by bertbert72** [comment]
Sounds like something wrong with the TV listing cache.  I'd start by deleting the pickle file and restarting.  Then if you aren't getting connected, there is hopefully something in the log.  

Depending on your network setup, you may need to use an IP address for your V6 box.  Some docker instances seem to have problems resolving local DNS names if they are set to use the Google DNS server.

**Comment by nicks123** [comment]
Hi, Deleted the pickle file and restarted, I can see in log unable to download tv change list.

> 2021-04-10 17:17:32 ERROR (SyncWorker_3) [custom_components.virgintivo.media_player] Unable to load channels from [https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)] code [200], trying cache
2021-04-10 17:17:32 ERROR (SyncWorker_3) [custom_components.virgintivo.media_player] Could not load cached version
2021-04-10 17:17:32 ERROR (SyncWorker_3) [custom_components.virgintivo.media_player] Could not fetch channel listings from https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK), error [Errno 2] No such file or directory: '/config/virgin_tivo.pickle'
2021-04-10 17:17:32 ERROR (SyncWorker_3) [custom_components.virgintivo.media_player] No channel configuration available
2021-04-10 17:17:37 ERROR (MainThread) [homeassistant.components.media_player] Error adding entities for domain media_player with platform virgintivo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 547, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 341, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/virgintivo/media_player.py", line 805, in device_state_attributes
    'base_channel_name': self._channels[self.get_sd_channel(self._channel_id)][CONF_NAME],
KeyError: None
2021-04-10 17:17:37 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up virgintivo platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 213, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 547, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 341, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/virgintivo/media_player.py", line 805, in device_state_attributes
    'base_channel_name': self._channels[self.get_sd_channel(self._channel_id)][CONF_NAME],
KeyError: None

>

**Comment by bertbert72** [comment]
Grab the latest version 0.1.20 and that should sort out the TV listings stuff.

**Comment by bertbert72** [comment]
If you are still having a problem, let me know otherwise I'll close this off.
